// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: event_response.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnterGameResponse 进入游戏响应
type EnterGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tip           string                 `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterGameResponse) Reset() {
	*x = EnterGameResponse{}
	mi := &file_event_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameResponse) ProtoMessage() {}

func (x *EnterGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameResponse.ProtoReflect.Descriptor instead.
func (*EnterGameResponse) Descriptor() ([]byte, []int) {
	return file_event_response_proto_rawDescGZIP(), []int{0}
}

func (x *EnterGameResponse) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

// ExitGameResponse 退出游戏响应
type ExitGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tip           string                 `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitGameResponse) Reset() {
	*x = ExitGameResponse{}
	mi := &file_event_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitGameResponse) ProtoMessage() {}

func (x *ExitGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitGameResponse.ProtoReflect.Descriptor instead.
func (*ExitGameResponse) Descriptor() ([]byte, []int) {
	return file_event_response_proto_rawDescGZIP(), []int{1}
}

func (x *ExitGameResponse) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

var File_event_response_proto protoreflect.FileDescriptor

const file_event_response_proto_rawDesc = "" +
	"\n" +
	"\x14event_response.proto\"%\n" +
	"\x11EnterGameResponse\x12\x10\n" +
	"\x03tip\x18\x01 \x01(\tR\x03tip\"$\n" +
	"\x10ExitGameResponse\x12\x10\n" +
	"\x03tip\x18\x01 \x01(\tR\x03tipB\x06Z\x04./pbb\x06proto3"

var (
	file_event_response_proto_rawDescOnce sync.Once
	file_event_response_proto_rawDescData []byte
)

func file_event_response_proto_rawDescGZIP() []byte {
	file_event_response_proto_rawDescOnce.Do(func() {
		file_event_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_response_proto_rawDesc), len(file_event_response_proto_rawDesc)))
	})
	return file_event_response_proto_rawDescData
}

var file_event_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_response_proto_goTypes = []any{
	(*EnterGameResponse)(nil), // 0: EnterGameResponse
	(*ExitGameResponse)(nil),  // 1: ExitGameResponse
}
var file_event_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_event_response_proto_init() }
func file_event_response_proto_init() {
	if File_event_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_response_proto_rawDesc), len(file_event_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_response_proto_goTypes,
		DependencyIndexes: file_event_response_proto_depIdxs,
		MessageInfos:      file_event_response_proto_msgTypes,
	}.Build()
	File_event_response_proto = out.File
	file_event_response_proto_goTypes = nil
	file_event_response_proto_depIdxs = nil
}
