run:
  timeout: 5m
  go: '1.26'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gofumpt
    - goimports
    - misspell
    - whitespace
    - gocyclo
    - gocognit
    - exhaustive
    - prealloc
    - thelper

linters-settings:
  gofumpt:
    extra-rules: true
  gocyclo:
    min-complexity: 50
  gocognit:
    min-complexity: 20
  exhaustive:
    default-signifies-exhaustive: true
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/byteweap/meta
