// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: envelope.proto

package envelope

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_UNKNOWN  MsgType = 0
	MsgType_RESPONSE MsgType = 1 // 服务端响应, mesh -> gate -> client
	MsgType_PUSH     MsgType = 2 // 服务端主推, mesh -> gate -> client
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "UNKNOWN",
		1: "RESPONSE",
		2: "PUSH",
	}
	MsgType_value = map[string]int32{
		"UNKNOWN":  0,
		"RESPONSE": 1,
		"PUSH":     2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`             // 序列(用户维度有序且唯一)
	Cmd           uint32                 `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`             // 指令(路由)
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`     // 版本
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳,ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Header) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 输入消息
// client -> gate -> mesh
type IMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`   // 头部信息
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"` // 目标服务名，由业务层进行约束
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // 业务消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMessage) Reset() {
	*x = IMessage{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMessage) ProtoMessage() {}

func (x *IMessage) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMessage.ProtoReflect.Descriptor instead.
func (*IMessage) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *IMessage) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *IMessage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *IMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 输出消息
// mesh -> gate -> client
type OMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`                                         // 头部信息
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`                                       // 发送方的服务名，由业务层进行约束
	MsgType       MsgType                `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3,enum=envelope.MsgType" json:"msg_type,omitempty"` // 消息类型
	Result        *Code                  `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`                                         // 消息结果
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                                       // 业务消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OMessage) Reset() {
	*x = OMessage{}
	mi := &file_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OMessage) ProtoMessage() {}

func (x *OMessage) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OMessage.ProtoReflect.Descriptor instead.
func (*OMessage) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *OMessage) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *OMessage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *OMessage) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_UNKNOWN
}

func (x *OMessage) GetResult() *Code {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *OMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Code struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 消息结果code, 0: 成功, 其它: 失败
	Tip           string                 `protobuf:"bytes,2,opt,name=tip,proto3" json:"tip,omitempty"`    // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Code) Reset() {
	*x = Code{}
	mi := &file_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Code) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Code) ProtoMessage() {}

func (x *Code) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Code.ProtoReflect.Descriptor instead.
func (*Code) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *Code) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Code) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\benvelope\"d\n" +
	"\x06Header\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\rR\x03cmd\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"h\n" +
	"\bIMessage\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.envelope.HeaderR\x06header\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xbe\x01\n" +
	"\bOMessage\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.envelope.HeaderR\x06header\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12,\n" +
	"\bmsg_type\x18\x03 \x01(\x0e2\x11.envelope.MsgTypeR\amsgType\x12&\n" +
	"\x06result\x18\x04 \x01(\v2\x0e.envelope.CodeR\x06result\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\",\n" +
	"\x04Code\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03tip\x18\x02 \x01(\tR\x03tip*.\n" +
	"\aMsgType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bRESPONSE\x10\x01\x12\b\n" +
	"\x04PUSH\x10\x02B#Z!github.com/byteweap/meta/envelopeb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_envelope_proto_goTypes = []any{
	(MsgType)(0),     // 0: envelope.MsgType
	(*Header)(nil),   // 1: envelope.Header
	(*IMessage)(nil), // 2: envelope.IMessage
	(*OMessage)(nil), // 3: envelope.OMessage
	(*Code)(nil),     // 4: envelope.Code
}
var file_envelope_proto_depIdxs = []int32{
	1, // 0: envelope.IMessage.header:type_name -> envelope.Header
	1, // 1: envelope.OMessage.header:type_name -> envelope.Header
	0, // 2: envelope.OMessage.msg_type:type_name -> envelope.MsgType
	4, // 3: envelope.OMessage.result:type_name -> envelope.Code
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
