// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: envelope.proto

package envelope

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 系统内部事件
type Event int32

const (
	Event_ONLINE    Event = 0 // 上线 [System]
	Event_OFFLINE   Event = 1 // 掉线 [System]
	Event_RECONNECT Event = 2 // 重连 [System]
	Event_Business  Event = 3 // 业务 [Business]
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "ONLINE",
		1: "OFFLINE",
		2: "RECONNECT",
		3: "Business",
	}
	Event_value = map[string]int32{
		"ONLINE":    0,
		"OFFLINE":   1,
		"RECONNECT": 2,
		"Business":  3,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

// 统一消息 envelope
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`        // 唯一标识
	App           string                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`         // 目标应用名
	Cmd           int32                  `protobuf:"varint,3,opt,name=cmd,proto3" json:"cmd,omitempty"`        // 指令(路由)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // 业务消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Envelope) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 统一消息 gate -> mesh
type Gate2MeshEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	E             *Envelope              `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
	Event         Event                  `protobuf:"varint,2,opt,name=event,proto3,enum=envelope.Event" json:"event,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gate2MeshEnvelope) Reset() {
	*x = Gate2MeshEnvelope{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gate2MeshEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gate2MeshEnvelope) ProtoMessage() {}

func (x *Gate2MeshEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gate2MeshEnvelope.ProtoReflect.Descriptor instead.
func (*Gate2MeshEnvelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Gate2MeshEnvelope) GetE() *Envelope {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *Gate2MeshEnvelope) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_ONLINE
}

func (x *Gate2MeshEnvelope) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\benvelope\"Z\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\x05R\x03cmd\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"n\n" +
	"\x11Gate2MeshEnvelope\x12 \n" +
	"\x01e\x18\x01 \x01(\v2\x12.envelope.EnvelopeR\x01e\x12%\n" +
	"\x05event\x18\x02 \x01(\x0e2\x0f.envelope.EventR\x05event\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid*=\n" +
	"\x05Event\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x01\x12\r\n" +
	"\tRECONNECT\x10\x02\x12\f\n" +
	"\bBusiness\x10\x03B\fZ\n" +
	"./envelopeb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envelope_proto_goTypes = []any{
	(Event)(0),                // 0: envelope.Event
	(*Envelope)(nil),          // 1: envelope.Envelope
	(*Gate2MeshEnvelope)(nil), // 2: envelope.Gate2MeshEnvelope
}
var file_envelope_proto_depIdxs = []int32{
	1, // 0: envelope.Gate2MeshEnvelope.e:type_name -> envelope.Envelope
	0, // 1: envelope.Gate2MeshEnvelope.event:type_name -> envelope.Event
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
